[versions]

kotlin = "2.4.10"

jgit = "7.7.0.202606012155-r"
kotest = "6.2.2"
kotlin-semver = "3.1.0"

best-practices = "0.10"
binary-compatibility-validator = "0.18.1"
dependency-analysis = "3.16.1"
detekt = "1.23.8"
github-release = "2.5.2"
gradle-testkit = "0.18"
publish-plugin = "2.1.1"
spotless = "8.8.0"
test-logger = "4.0.0"
testkit-support = "0.18"

[libraries]

jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
kotlin-semver = { module = "io.github.z4kn4fein:semver", version.ref = "kotlin-semver" }

kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
testkit-support = { module = "com.autonomousapps:gradle-testkit-support", version.ref = "testkit-support" }

[plugins]

best-practices = { id = "com.autonomousapps.plugin-best-practices-plugin", version.ref = "best-practices" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
github-release = { id = "com.github.breadmoirai.github-release", version.ref = "github-release" }
gradle-testkit = { id = "com.autonomousapps.testkit", version.ref = "gradle-testkit" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
publish-plugin = { id = "com.gradle.plugin-publish", version.ref = "publish-plugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger" }
