name: PR Autolabeler

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches-ignore:
      - 'renovate/**'

jobs:
  autolabel-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Figure shared actions
        uses: actions/checkout@v3
        with:
          repository: FigureTechnologies/shared-actions
          ref: v1
          token: ${{ secrets.PAT }}
          path: shared-actions

      - name: Autolabeler
        uses: ./shared-actions/autolabeler
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
